### PR TITLE
add formatting section

### PR DESCRIPTION
**Pull request by rodrigodavies**

### CODE REVIEW

**Comment by josemarluedke** [comment]
:shipit:

**Comment by gustavoguichard** [comment]
@jasewilson 
:shipit:

**Comment by jasewilson** [comment]
YES.

Would be cool to see <sup>$</sup>1234.<sup>56</sup>  superscript dollar sign and decimal places if possible

Otherwise 
:shipit:

**Comment by jasewilson** [comment]
Future add-ons:

* Time in various situations
* Date in various situations
* Footnote symbols (e.g. <sup>†</sup>, <sup>*</sup>, etc.

**Pull request merged**
